### ISSUE TITLE
Suporte ao ambiente de sandbox

### ISSUE THREAD

**Issue by davidkwast** [rochacbruno/python-pagseguro#21]
Boa noite,

Estou usando o módulo no ambiente de sandbox do PagSeguro. Estou tendo que modificar o objeto config. Se tudo der certo, envio o DIFF.

**Comment by ellisonleao** [comment]
:+1:

**Comment by rochacbruno** [comment]
:+1: nem sabia que tinham implementado um sandbox!

**Comment by davidkwast** [comment]
Pretendo modificar como o Config() é instanciado, pelo menos com a opção de SANDBOX. E também permitir que um objeto de config seja passado na criação do PagSeguro().

Não tenho muita experiência com versionamento em geral, qual a forma ideial para submeter estas proposta para o projeto aqui? Seria a saída do "git diff" ou seria um comando mais específico? E por onde eu envio?

**Comment by relsi** [comment]
@davidkwast o ideal seria tu fazer um branch no teu fork com essas modificações e enviar um pull request para o @rochacbruno verificar e efetuar o merge no repositório original. Da uma lida nesse material que pode ajudar no processo https://help.github.com/categories/collaborating/

**Comment by luzfcb** [comment]
@davidkwast da uma olhada nessa vídeo aula também: http://www.youtube.com/watch?v=UMhskLXJuq4 
ela vai lhe ser bem util

**Comment by davidkwast** [comment]
Obrigado. Então aguardem mais uns dias. Ainda tenho que fazer as modificações e testar.

**Comment by davidkwast** [comment]
Usei a própria interface e copiei e colei do código, gerando dois pull requests. Meu teste deu certo. Por favor vejam se está de acordo as guidelines do projeto.

Abraços

**Comment by ellisonleao** [comment]
@davidkwast agora temos uma class abstrata que contém a configuração básica a ser usada e extendida quando instanciamos uma instancia do `Pagseguro`. Precisamos adicionar as configs do de sandbox lá https://github.com/rochacbruno/python-pagseguro/blob/master/pagseguro/configs.py#L6

**Comment by davidkwast** [comment]
Quando eu puder, farei isto. Obrigado

**Comment by ellisonleao** [comment]
@rochacbruno acho que podemos fechar essa, não?
