### ISSUE TITLE
Config Docs

### ISSUE THREAD

**Issue by ellisonleao** [rochacbruno/python-pagseguro#27]
Precisamos criar uma doc básica explicando como extender a classe de Configuração.

**Comment by tir4y** [comment]
@ellisonleao, a doc foi criada? Como faço para utilizar o python-pagseguro como sandbox?

**Comment by ellisonleao** [comment]
Ainda não @tir4y !  Mas um exemplo básico é usar a classe `ConfigSandbox` quando instanciar um objeto `PagSeguro`

```
from pagseguro import PagSeguro
from pagseguro.configs import ConfigSandbox

pg = PagSeguro(email="seuemail@dominio.com", token="ABCDEFGHIJKLMNO", config=ConfigSandBox())
```

Não testei o código acima, se tiver algum problema avisa pra gente.

**Comment by tir4y** [comment]
@ellisonleao obrigado pelo breve retorno! já vou realizar os testes!

**Comment by tir4y** [comment]
@ellisonleao, o ConfigSandbox() não está vindo no setup do comando pip install pagseguro.
Eu abri a classe configs, que está na minha lib python, e lá so tinha a que está abaixo.
Eu copiei a que está no config do git e consegui importar.

class Config(object):
    def get(self, key, default=None):
        return getattr(self, key, default)

    BASE_URL = "https://ws.pagseguro.uol.com.br"
    VERSION = "/v2/"
    CHECKOUT_SUFFIX = VERSION + "checkout"
    CHARSET = "UTF-8"  # ISO-8859-1
    NOTIFICATION_SUFFIX = VERSION + "transactions/notifications/%s"
    TRANSACTION_SUFFIX = VERSION + "transactions/%s"
    QUERY_TRANSACTION_SUFFIX = VERSION + "transactions"
    CHECKOUT_URL = BASE_URL + CHECKOUT_SUFFIX
    NOTIFICATION_URL = BASE_URL + NOTIFICATION_SUFFIX
    TRANSACTION_URL = BASE_URL + TRANSACTION_SUFFIX
    QUERY_TRANSACTION_URL = BASE_URL + QUERY_TRANSACTION_SUFFIX
    CURRENCY = "BRL"
    CTYPE = "application/x-www-form-urlencoded; charset={0}".format(CHARSET)
    HEADERS = {"Content-Type": CTYPE}
    REFERENCE_PREFIX = "REF%s"
    PAYMENT_HOST = "https://pagseguro.uol.com.br"
    PAYMENT_URL = PAYMENT_HOST + CHECKOUT_SUFFIX + "/payment.html?code=%s"

    DATETIME_FORMAT = '%Y-%m-%dT%H:%M:%S'

**Comment by ellisonleao** [comment]
@tir4y esqueci que a versão atual não está no pypi ainda, você pode testar instalando a versão dev por enquanto.

```
pip install -e git+https://github.com/rochacbruno/python-pagseguro.git
```

**Comment by tir4y** [comment]
Valeu!

**Comment by ellisonleao** [comment]
@rochacbruno Cê manda o bump da version?

**Comment by rochacbruno** [comment]
done! @ellisonleao

**Comment by rochacbruno** [comment]
@ellisonleao  You have the rights to run "setup.pu sdist upload" you are listed there as maintainer :)

**Comment by tir4y** [comment]
@ellisonleao tem alguma previsão de quando vão subir esta versão no pip? 
Abracos.

**Comment by rochacbruno** [comment]
@tir4y  já subiu

**Comment by ellisonleao** [comment]
@rochacbruno :+1:
