### ISSUE TITLE
Esta biblioteca possui suporte a assinaturas?

### ISSUE THREAD

**Issue by rodfersou** [rochacbruno/python-pagseguro#41]
https://pagseguro.uol.com.br/para_seu_negocio/assinaturas.jhtml

**Comment by rochacbruno** [comment]
@rodfersou sim!

https://github.com/rochacbruno/python-pagseguro/blob/master/pagseguro/__init__.py#L139

basta informar o dicionario `pre_approval={'period': "MONTHLY, ...."}` com os atributos

- `charge`: "manual"
- `name`: "Assinatura da Revista XYZ"
- `details`: "Todo dia 10 de cada mês será cobrado o valor de R$150,00"
- `amount_per_payment`: '150.00'
- `period`: 
    - WEEKLY para toda semana;
    - MONTHLY para todo mês;
    - BIMONTHLY para a cada dois meses;
    - TRIMONTHLY para cada três meses;
    - SEMIANNUALLY a cada seis meses.
    - YEARLY para cada ano;

Outros dados opcionais são:max_amount_per_payment, max_payments_per_period, max_amount_per_period, initial_date, final_date, max_total_amount

E você ainda pode passar outros atributos `raw` como na documentacao da API.

**Comment by rodfersou** [comment]
maravilha! obrigado

**Comment by rodfersou** [comment]
Percebi que esse exemplo está na versão mais nova da API, que está defasada com relação ao release Pypi.

@rochacbruno voce tem idéia de quando será gerado um novo release?

**Comment by rodfersou** [comment]
ou se possível, poderia por favor me passar o exemplo de como criar uma assinatura na versão que está no Pypi?

**Comment by rochacbruno** [comment]
Vou atualizar a versão no PyPi hoje.

**Comment by rochacbruno** [comment]
por enquanto pode usar

`pip install https://github.com/rochacbruno/python-pagseguro/tarball/master`

**Comment by rodfersou** [comment]
Eu tentei fazer alguns testes no sandbox usando essa sua sugestão de configuração (e meu token do sandbox..)

Sempre recebo a seguinte mensagem de erro:
11024 - Items invalid quantity.

Algumas pessoas também reclamaram do sandbox, talvez não seja usável para testar assinaturas: http://forum.pagseguro.uol.com.br/t/11625742/erro-messageitems-invalid-quantitymessage

Confirma?

**Comment by rodfersou** [comment]
@rochacbruno eu removi as mensagens questionando o release por que depois de ler um pouco do código na revisão do release consegui me encontrar..

De qualquer forma obrigado

**Comment by rodfersou** [comment]
Consegui dessa forma:

```python
pg = PagSeguro(
    token=TOKEN, email=EMAIL, config=ConfigSandbox())
pg.pre_approval = dict(
    amount_per_payment='30.00',
    charge='manual',
    name='XYZ Magazine Subscription',
    period='MONTHLY',
    max_total_amount='30.00',
    max_amount_per_period='30.00',
    final_date=_final_date()
)
pg.items = [
    {'id': '0001', 'description': 'XYZ Magazine Subscription', 'amount': '30.00', 'quantity': 1}
]
pg.sender = {
    'email': 'c96595836663849248355@sandbox.pagseguro.com.br'
}
pg.redirect_url = 'http://www.google.com'
response = self.pg.checkout()
# https://sandbox.pagseguro.uol.com.br/v2/checkout/payment.html?code=94D6B484171712B664732FAFB8407B85
print response.payment_url
```

Mas quando tento abrir a URL aparece a mensagem de **Página não encontrada**.

**Comment by ellisonleao** [comment]
Apenas uma pequena correção. Na versão na `master` mudamos a forma de instanciar a configuração.  Agora o config é apenas um dict, onde você pode fazer alguns overrides em algumas variáveis pré-definidas:

Ex:

```python
from pagseguro import PagSeguro

config = {'sandbox': True}
pg = PagSeguro(token=TOKEN, email=EMAIL, config=config)
```

**Comment by rodfersou** [comment]
Mudei somente as configurações do sandbox para produção, e a página apareceu.

Obrigado

**Comment by Hernany** [comment]
O atributo CHARGE recebe qual valor para a recorrencia controlada pelo Pagseguro. Seria "auto" como na documentação?

**Comment by Hernany** [comment]
Só está funcionando como "manual". Como "auto" o fluxo é interrompido!
