### ISSUE TITLE
Dependências e gerenciamento de versões

### ISSUE THREAD

**Issue by hvelarde** [rochacbruno/python-pagseguro#46]
Gostaria saber porque estão fixando as versões das dependência desse jeito:

https://github.com/rochacbruno/python-pagseguro/blob/master/requirements.txt

Existe alguma razão para fixar uma versão específica usando `==` e não utilizar a notação `>=` ou simplesmente não fixar?

Isso pode trazer problemas nas integrações sobre todo em pacotes amplamente utilizados como é o caso do **requests**.

https://pip.readthedocs.io/en/1.1/requirements.html

**Comment by rochacbruno** [comment]
@hvelarde não tem razão especifica, mas você tem razão, vou alterar o arquivo de requirementes.

**Comment by hvelarde** [comment]
valeu!
