### ISSUE TITLE
AttributeError 'dict' object has no attribute 'PAYMENT_URL'

### ISSUE THREAD

**Issue by gileno** [rochacbruno/python-pagseguro#48]
No trecho de código:

```
class XMLParser(object):
    def __init__(self, xml, config=None):
        self.xml = xml
        self.errors = None
        self.config = config or {}
        self.parse_xml(xml)
        logger.debug(self.__dict__)

```

Se o "config" passado para o Parser não tiver alterações ou apenas for sandbox=True, o dict será vazio então no Parser não terá uma instância de Config, terá um dict vazio e irá gerar erro na classe PagSeguroCheckoutResponse quando for necessário pegar a url de pagamento (PAYMENT_URL).

Estou gerando pull request com uma possível solução

**Comment by rochacbruno** [comment]
Fixed in #49
