### ISSUE TITLE
Problemas com clean_none_params()

### ISSUE THREAD

**Issue by jdcarvalho** [rochacbruno/python-pagseguro#51]
Olá pessoal,

recentemente contribui com o projeto com a possibilidade de usar ou não o endereço no checkout através do parâmetro shippingAddressRequired. Estando como False o mesmo não requer endereços para utilizar o checkout para serviços. Encontrei um pequeno problema com o uso deste parâmetro. Debugando o código, conforme prints percebi que o problema está no método clean_none_params(), linha 164 do __init__.py

O parâmetro é preenchido como False corretamente mas o clean_none_params o remove.

Como isso certamente é uma decisão de projeto pelo uso do clean_none_params, gostaria de saber de vocês como posso implementar um fix para o que o clean_none_params continue fazendo o seu trabalho e possa também aceitar booleanos False.

Pensei em uma checagem de tipo para ignorar a limpeza de booleanos False mas gostaria de partilhar com vocês antes a fim de obter a melhor solução,

Atenciosamente,

João Carvalho

![1](https://cloud.githubusercontent.com/assets/1715039/20722747/edac8c28-b64e-11e6-8f9a-6f5e05f2d420.png)
![2](https://cloud.githubusercontent.com/assets/1715039/20722748/edcab360-b64e-11e6-9a28-bcf2a5bace11.png)

**Comment by rochacbruno** [comment]
Esta linha https://github.com/rochacbruno/python-pagseguro/blob/master/pagseguro/__init__.py#L188

deve mudar de

```python
    def clean_none_params(self):
        copy = dict(self.data)
        for k, v in list(copy.items()):
            if not v:
                del self.data[k]
```

para

```python
    def clean_none_params(self):
        copy = dict(self.data)
        for k, v in list(copy.items()):
            if v is None:
                del self.data[k]
```

usar **is None** é a forma correta.

**Comment by rochacbruno** [comment]
@jdcarvalho na verdade dá para simplificar

```python
In [4]: data
Out[4]: {'1': 'b', '2': False, '4': None}

In [5]: {k: v for k, v in data.items() if v is not None}
Out[5]: {'1': 'b', '2': False}
```

então

```python
 def clean_none_params(self):
     self.data = {k: v for k, v in self.data.items() if v is not None}
```

**Comment by jdcarvalho** [comment]
Perfeito Bruno! Era isso mesmo que tinha em mente. o Segundo snippet ficou bem mais interessante com a compreensão de dicionário. Posso aplicar o fix e solicitar o pull para integração ou você faz isso por ai?

**Comment by rochacbruno** [comment]
Se puder mandar um PR é melhor :)
