### ISSUE TITLE
Existe Split de Pagamento? 

### ISSUE THREAD

**Issue by Iazzetta** [rochacbruno/python-pagseguro#54]
Gostaria de saber se voces implementaram o Split de Pagamentos.
Onde eu cadastro recebedores e crio um split entre eles onde meu recebedor principal recebe uma porcentagem do valor e o resto já é atribuido aos recebedores. Obrigado!

**Comment by rochacbruno** [comment]
@Iazzetta quando criei a lib o PagSeguro não tinha essa funcionalidade, não está implementado, mas se é algo disponivel na API pode ser facilmente implementado.

**Comment by Iazzetta** [comment]
Então, eu andei pesquisando e o Pagseguro não está disponibilizando a api de split de pagamentos. Muita gente reclamando. Se ao menos tivesse disponivel na API, eu daria um fork e ajudaria voces. Obrigado!
