### ISSUE TITLE
Checkout falha ao desativar USE_SHIPPING=False

### ISSUE THREAD

**Issue by brunolmfg** [rochacbruno/python-pagseguro#67]
Desabilitando o uso de endereço para entrega, através da opção `use_shipping`, o _checkout_ falha.

Exemplo:

```python
from pagseguro import PagSeguro

config = {'sandbox': True, 'use_shipping': False}
pg = PagSeguro(email="seuemail@dominio.com", token="ABCDEFGHIJKLMNO", config=config)
```

Ao realizar o _checkout_ a seguinte resposta é retornada pelo PagSeguro:

```xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<errors>
  <error>
    <code>11056</code>
    <message>sender address required invalid value: False</message>
  </error>
</errors>
```

O problema ocorre porque o `requests` encoda os parâmetros booleanos com a primeira letra capital, ou seja, `'True'` ou `'False'`. Dessa forma, o serviço do PagSeguro não reconhece o valor `'False'` como válido no parâmetro `shippingAddressRequired`.

```python
            params['shippingAddressRequired'] = False
```
Uma solução seria substituir `False` na atribuição acima para a `string` `'false'`, como segue:
```python
            params['shippingAddressRequired'] = 'false'
```

**Comment by lepri** [comment]
Tem alguma previsão de quando esse fix será lançado?
