### ISSUE TITLE
Pip para pipenv

### ISSUE THREAD

**Issue by MarcusMann** [rochacbruno/python-pagseguro#70]
Estou abrindo essa issue para debater um assunto interessante, que tal adotarmos o uso do pipenv aqui dentro do projeto? @mazulo @rochacbruno

**Comment by rochacbruno** [comment]
AFAIK o pipenv não serve para bibliotecas, apenas para aplicações.

Se for para adotar o Poetry ai pode ser que funcione.

Mas qual o problema que esta tentando resolver? qual problema encontrou no uso do setuptools?

**Comment by MarcusMann** [comment]
@rochacbruno verdade, eu tivjaie na maionese... esqueci que era uma LIB. Não encontrei problema algum, ta funcionando perfeitamente. 

Neste caso eu acho que vou fechar essa issue como **solved**.
